DeliverIT/Controllers/AdminController.cs
using DeliverIT.Services.Exceptions;
using DeliverIT.Services.Services.ServicesInterfaces;
using DeliverIT.Web.Helpers;
using DeliverIT.Web.Helpers.HelpersContracts;
using DeliverIT.Web.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace DeliverIT.Web.Controllers
{
    public class AdminController : Controller
    {
        private readonly IWarehouseService warehouseService;
        private readonly IEmployeeService employeeService;
        private readonly ICustomerService customerService;
        private readonly IModelMapper modelMapper;
        private readonly IAuthHelper authHelper;
        private readonly ICityService cityService;
        private readonly ICountryService countryService;

        public AdminController(IWarehouseService warehouseService
            , IEmployeeService employeeService
            , ICustomerService customerService
            , IModelMapper modelMapper
            , IAuthHelper authHelper
            , ICityService cityService
            , ICountryService countryService)
        {
            this.warehouseService = warehouseService;
            this.employeeService = employeeService;
            this.customerService = customerService;
            this.modelMapper = modelMapper;
            this.authHelper = authHelper;
            this.cityService = cityService;
            this.countryService = countryService;
        }


        [HttpGet]
        [MyAuthorisation(Role = "Employee")]
        public IActionResult Index()
        {
            ViewData["EmployeeName"] = this.HttpContext.Session.GetString("CurrentUser");
            ViewData["UserId"] = int.Parse(this.HttpContext.Session.GetString("UserId"));
            var employeeId = this.HttpContext.Session.GetString("UserId");
            var allShipments = this.warehouseService.GetIncomingShipments(int.Parse(employeeId));
            return this.View(allShipments);
        }
        [MyAuthorisation(Role = "Employee")]
        public IActionResult Customers()
        {
            var customers = customerService.GetAll();
            return View(customers);
        }
        [MyAuthorisation(Role = "Employee")]
        public IActionResult Employees()
        {
            var employees = employeeService.GetAll();
            return View(employees);

        }
        [HttpPost]
        [MyAuthorisation(Role = "Employee")]
        public IActionResult SearchCustomer(string searchword)
        {
            try
            {
                var customers = this.customerService.SearchAllFields(searchword);
                return this.View("Customers", customers);
            }
            catch (InvalidInputDataException)
            {
                return this.View();
            }

        }


        [HttpPost]
        [MyAuthorisation(Role = "Employee")]
        public IActionResult UpcomingShipment(int warehouseId)
        {
            try
            {
                var upcomingShipment = this.warehouseService.GetNextOrder(warehouseId);
                return this.View("../Shipment/UpcomingShipment", upcomingShipment);
            }
            catch (EntityNotFoundException)
            {
                return this.RedirectToAction(nameof(this.Index));
            }

        }


        [MyAuthorisationAttribute(Role = "Employee")]
        public IActionResult Edit(int id)
        {
            try
            {
                var employee = this.employeeService.GetById(id);
                var customerViewModel = this.modelMapper.ToViewModel(employee);

                return this.EmployeeView(customerViewModel);
            }
            catch (EntityNotFoundException)
            {
                return this.View("Error");
            }
        }
        [MyAuthorisationAttribute(Role = "Employee")]
        [HttpPost]
        public IActionResult Edit(int id, [Bind("FirstName, LastName, Email, Password, Street,CityId,CountryId,ConfirmPassword,WarehouseId")] EmployeeViewModel customerViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(customerViewModel);
            }

            if (!customerViewModel.Password.Equals(customerViewModel.ConfirmPassword))
            {
                this.ModelState.AddModelError("ConfirmPassword", "Confirm password should match password.");
                return this.View(customerViewModel);
            }
            var user = this.modelMapper.ToModel(customerViewModel);
            this.employeeService.Update(id, user);

            return this.RedirectToAction("Logout", "Account");
        }

        [MyAuthorisation(Role = "Employee")]
        public IActionResult Create()
        {
            var newEmployeeView = new EmployeeViewModel();
            return this.EmployeeView(newEmployeeView);

        }

        [HttpPost]
        [MyAuthorisation(Role = "Employee")]
        public IActionResult Create([Bind("FirstName,LastName,Email,Street,CityId,CountryId,WarehouseId,Password,ConfirmPassword")] EmployeeViewModel employeeView)
        {
            if (!this.ModelState.IsValid)
            {
                return this.EmployeeView(employeeView);
            }

            if (this.authHelper.Exist(employeeView.Email))
            {
                this.ModelState.AddModelError("Email", "User with same email already exists.");
                return this.EmployeeView(employeeView);
            }

            if (!employeeView.Password.Equals(employeeView.ConfirmPassword))
            {
                this.ModelState.AddModelError("ConfirmPassword", "Confirm password should match password.");
                return this.EmployeeView(employeeView);
            }

            try
            {
                var employee = modelMapper.ToModel(employeeView);
                this.employeeService.Create(employee);
                return this.RedirectToAction(nameof(this.Index));
            }
            catch (DuplicateEntityException)
            {
                return View("Error");
            }
        }

        private IActionResult EmployeeView(EmployeeViewModel employeeView)
        {
            employeeView.Warehouses = GetWarehouses();
            employeeView.Cities = GetCities();
            employeeView.Countries = GetCountries();
            return this.View(employeeView);
        }

        private SelectList GetWarehouses()
        {
            var warehouses = this.warehouseService.GetAll();
            return new SelectList(warehouses, "WarehouseId", "Address");
        }
        private SelectList GetCities()
        {
            var cities = this.cityService.GetAll().ToList();
            return new SelectList(cities, "CityId", "City");
        }
        private SelectList GetCountries()
        {
            var countries = this.countryService.GetAll().ToList();
            return new SelectList(countries, "CountryId", "CountryName");
        }


    }
}

DeliverIT/Controllers/ParcelController.cs
using DeliverIT.Services.Exceptions;
using DeliverIT.Services.Services.ServicesInterfaces;
using DeliverIT.Web.Helpers;
using DeliverIT.Web.Helpers.HelpersContracts;
using DeliverIT.Web.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace DeliverIT.Web.Controllers
{
    public class ParcelController : Controller
    {
        private readonly IParcelService parcelService;
        private readonly IModelMapper modelMapper;
        private readonly ICustomerService customerService;
        private readonly IShipmentService shipmentService;
        private readonly IWarehouseService warehouseService;

        public ParcelController(IParcelService parcelService
                               , IModelMapper modelMapper
                               , ICustomerService customerService
                               , IShipmentService shipmentService
                               , IWarehouseService warehouseService)
        {
            this.parcelService = parcelService;
            this.modelMapper = modelMapper;
            this.customerService = customerService;
            this.shipmentService = shipmentService;
            this.warehouseService = warehouseService;
        }
        [HttpGet]
        [MyAuthorisation(Role = "Employee")]
        public IActionResult Index()
        {
            var allParcels = this.parcelService.GetAll();
            return View(allParcels);
        }
        [MyAuthorisation(Role = "Employee")]
        public IActionResult Create()
        {
            var newParcelViewModel = new ParcelViewModel();
            return this.ParcelView(newParcelViewModel);

        }
        [HttpPost]
        [MyAuthorisation(Role = "Employee")]
        public IActionResult Create([Bind("WarehouseId,Weight,CategoryId,ShipmentId,CustomerId,HomeDelivery")] ParcelViewModel parcelViewModel)
        {
            if (!ModelState.IsValid)
            {
                return ParcelView(parcelViewModel);
            }
            try
            {
                var parcel = modelMapper.ToModel(parcelViewModel);
                this.parcelService.Create(parcel);
                return this.RedirectToAction(nameof(this.Index));
            }
            catch (DuplicateEntityException)
            {
                return View("Error");
            }
        }
        [MyAuthorisation(Role = "Employee")]
        public IActionResult Edit(int id)
        {
            try
            {
                var parcel = this.parcelService.Get(id);
                var parcelViewModel = this.modelMapper.ToViewModel(parcel);

                return this.ParcelView(parcelViewModel);
            }
            catch (EntityNotFoundException)
            {
                return this.View("Error");
            }
        }
        [HttpPost]
        [MyAuthorisation(Role = "Employee")]
        public IActionResult Edit(int id, [Bind("WarehouseId,Weight,CategoryId,ShipmentId,CustomerId,HomeDelivery")] ParcelViewModel parcelViewModel)
        {
            if (!ModelState.IsValid)
            {
                return ParcelView(parcelViewModel);
            }
            try
            {
                var parcel = modelMapper.ToModel(parcelViewModel);
                this.parcelService.Update(id, parcel);
                return this.RedirectToAction(nameof(this.Index));
            }
            catch (EntityNotFoundException)
            {
                return View("Error");
            }
        }
        [MyAuthorisation(Role = "Employee")]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                this.parcelService.Delete(id);
            }
            catch (EntityNotFoundException)
            {
                return this.View("Error");
            }

            return this.RedirectToAction(nameof(this.Index));
        }
        private IActionResult ParcelView(ParcelViewModel parcelView)
        {
            parcelView.Shipment = GetShipments(parcelView.WarehouseId);
            parcelView.Customer = GetCustomers();
            parcelView.Category = GetCategories();
            parcelView.Warehouse = GetWarehouses();
            return this.View(parcelView);
        }

        //Gets shipments with status preparing in the warehouse that the parcel is in.
        private SelectList GetShipments(int warehouseId)
        {
            var shipments = this.shipmentService.GetAll()
                .Where(x => x.Status == "Preparing" && x.OriginId == warehouseId);
            return new SelectList(shipments, "ShipmentId", "FromTo");
        }
        private SelectList GetCategories()
        {
            var parcels = this.parcelService.GetAllCategories();
            return new SelectList(parcels, "CategoryId", "Name");
        }
        private SelectList GetCustomers()
        {
            var customers = this.customerService.GetAll();
            return new SelectList(customers, "CustomerId", "FirstName", "LastName");
        }
        private SelectList GetWarehouses()
        {
            var warehouses = this.warehouseService.GetAll();
            return new SelectList(warehouses, "WarehouseId", "Address");
        }
    }
}

DeliverIT/Controllers/ShipmentController.cs
using DeliverIT.Services.Exceptions;
using DeliverIT.Services.Services.ServicesInterfaces;
using DeliverIT.Web.Helpers;
using DeliverIT.Web.Helpers.HelpersContracts;
using DeliverIT.Web.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace DeliverIT.Web.Controllers
{
    public class ShipmentController : Controller
    {
        private readonly IShipmentService shipmentService;
        private readonly IModelMapper modelMapper;
        private readonly IWarehouseService warehouseService;
        private readonly IParcelService parcelService;

        public ShipmentController(IShipmentService shipmentService, IModelMapper modelMapper, IWarehouseService warehouseService, IParcelService parcelService)
        {
            this.shipmentService = shipmentService;
            this.modelMapper = modelMapper;
            this.warehouseService = warehouseService;
            this.parcelService = parcelService;
        }
        [MyAuthorisationAttribute(Role = "Employee")]
        public IActionResult Index()
        {
            var shipments = shipmentService.GetAll();
            return View(shipments);
        }
        [MyAuthorisationAttribute(Role = "Employee")]
        public IActionResult Create()
        {
            var shipmentViewModel = new ShipmentViewModel();
            return ShipmentView(0, shipmentViewModel);
        }
        [HttpPost]
        [MyAuthorisationAttribute(Role = "Employee")]
        public IActionResult Create([Bind("OriginId,DestinationId,DepartureDate,ArrivalDate,ShipmentId,Parcels,Status")] ShipmentViewModel shipmentViewModel)
        {
            if (!ModelState.IsValid || shipmentViewModel.OriginId == shipmentViewModel.DestinationId)
            {
                return ShipmentView(0, shipmentViewModel);
            }
            try
            {
                var shipment = modelMapper.ToModel(shipmentViewModel);
                shipmentService.Create(shipment);
                return this.RedirectToAction(nameof(this.Index));
            }
            catch (DuplicateEntityException)
            {
                return View("Error");
            }
        }
        [MyAuthorisationAttribute(Role = "Employee")]
        public IActionResult Edit(int id)
        {
            try
            {
                var shipmentToUpdate = shipmentService.GetById(id);
                var shipmentViewModel = modelMapper.ToViewModel(shipmentToUpdate);
                return ShipmentView(id, shipmentViewModel);
            }
            catch (EntityNotFoundException)
            {
                return View("Error");
            }
        }

        [HttpPost]
        [MyAuthorisationAttribute(Role = "Employee")]
        public IActionResult Edit(int id, [Bind("OriginId,DestinationId,DepartureDate,ArrivalDate,ShipmentId,Parcels,Status")] ShipmentViewModel shipmentViewModel)
        {
            if (!ModelState.IsValid || shipmentViewModel.OriginId == shipmentViewModel.DestinationId)
            {
                return ShipmentView(id, shipmentViewModel);
            }
            try
            {
                shipmentViewModel.ShipmentId = id;
                var shipment = modelMapper.ToModel(shipmentViewModel);
                shipmentService.Update(id, shipment);
                return this.RedirectToAction(nameof(this.Index));
            }
            catch (DuplicateEntityException)
            {
                return View("Error");
            }
        }
        [MyAuthorisation(Role = "Employee")]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                this.shipmentService.Delete(id);
            }
            catch (EntityNotFoundException)
            {
                return this.View("Error");
            }

            return this.RedirectToAction(nameof(this.Index));
        }
        private IActionResult ShipmentView(int id, ShipmentViewModel shipmentViewModel)
        {
            var warehouses = GetWarehouses();
            shipmentViewModel.OriginWarehouse = warehouses;
            shipmentViewModel.DestinationWarehouse = warehouses;
            shipmentViewModel.UnselectedParcels = GetUnselectedParcels(id, shipmentViewModel.OriginId);
            return View(shipmentViewModel);
        }

        //Gets all parcels that are with no shipment
        private List<SelectListItem> GetUnselectedParcels(int id, int originWarehouseId)
        {
            var parcels = this.shipmentService.GetAllOtherParcels(id, originWarehouseId)
                .Select(x => new SelectListItem()
                {
                    Value = x.ParcelId.ToString(),
                    Text = $"ID:' {x.ParcelId} ' , Location :' {x.Warehouse} ' Customer: '{x.CustomerName}' , Category: ' {x.Category} '"
                }).ToList();
            return parcels;
        }
        private SelectList GetWarehouses()
        {
            var warehouses = this.warehouseService.GetAll().ToList();
            return new SelectList(warehouses, "WarehouseId", "Address");
        }
        [MyAuthorisationAttribute(Role = "Employee")]
        public IActionResult ParcelList()
        {
            return this.View();
        }
    }
}

DeliverIT/Views/Shared/PermissionDenied.cshtml
<div class="centered" style="margin-top:30px">
    <h2>
        ACCESS DENIED <br />
    </h2>
</div>
<div style="display: flex;
          justify-content: center;">
    <img src="~/css/Images/AccessDenied.png" style="height:500px" img />
</div>

<div class="centered">
    <p>
        You don't have permission to view this page. <br />
        Go back to <a asp-controller="Home" asp-action="Index" class="orange">Home</a>
    </p>
</div>

DeliverIT/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@{
    this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("CurrentUser");
    this.ViewData["CurrentUser"] = this.Context.Session.GetString("CurrentUser");
    this.ViewData["UserRole"] = this.Context.Session.GetString("UserRole");
}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>DeliverIT - @ViewData["Title"]</title>
    <link rel="stylesheet" href="/css/lib/dist/bootstrap.css" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
    <link href="https://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css" rel="stylesheet" type="text/css" />

    @RenderSection("Styles", false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="~/css/Images/deliverit_whiteAndOrange.png" img height="30" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a asp-controller="Warehouse" asp-action="Index" class="nav-link">Locations</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Pricing" class="nav-link">Pricing</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="About" class="nav-link">About</a>
                        </li>
                        @if ((bool)ViewData["IsAuthenticated"])
                        {
                            if (ViewData["UserRole"].Equals("Employee"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Management</a>
                                    <div class="dropdown-menu">
                                        <a asp-controller="Admin" asp-action="Index" class="dropdown-item">Admin Panel</a>
                                        <div class="dropdown-divider"></div>
                                        <a asp-controller="Parcel" asp-action="Index" class="dropdown-item">Parcels</a>
                                        <a asp-controller="Shipment" asp-action="Index" class="dropdown-item">Shipments</a>
                                        <a asp-controller="Warehouse" asp-action="Index" class="dropdown-item">Locations</a>
                                        <a asp-controller="Admin" asp-action="Customers" class="dropdown-item">Customers</a>
                                        <a asp-controller="Admin" asp-action="Employees" class="dropdown-item">Employees</a>
                                    </div>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
                                    <div class="dropdown-menu">
                                        <a asp-controller="Customer" asp-action="Index" class="dropdown-item">My information</a>
                                        <div class="dropdown-divider"></div>
                                        <a asp-controller="Customer" asp-action="IncomingParcels" class="dropdown-item">Incoming Parcels</a>
                                        <a asp-controller="Customer" asp-action="PastParcels" class="dropdown-item">Past Parcels</a>
                                    </div>
                                </li>
                            }
                        }
                    </ul>

                    <ul class="navbar-nav ms-md-auto">
                        <li>
                            @if ((bool)ViewData["IsAuthenticated"])
                            {
                                <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
                            }
                            else
                            {
                                <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        @RenderBody()
    </div>
    <footer class="card-footer">
        <div class="container centered">
            <div class="grid-item">&copy; @DateTime.Now.Year - DeliverIT - Mihail Matov & Miroslav Petrov - <a class="orange" asp-controller="Home" asp-action="About">About</a> - <a class="orange" href="#top">Back to top</a></div>
            <span style="padding: 10px">  Phone: +359 885 555 5555</span>
            <span>  Email: info@deliverit.com</span>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/js/bootstrap-multiselect.js" type="text/javascript"></script>

</body>
</html>