DeliverIT/Models/ViewModels/CustomerViewModel.cs
using DeliverIT.Models;
using DeliverIT.Services.DTOs;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DeliverIT.Web.Models.ViewModels
{
    public class CustomerViewModel : CustomerWeb
    {
        public int CustomerId { get; set; }
        [Required]
        public string ConfirmPassword { get; set; }
        public SelectList Cities { get; set; }
        public SelectList Countries { get; set; }
        public string Address { get; set; }
        public List<ParcelDto> CustomerParcels { get; set; }
    }
}

DeliverIT/Models/ViewModels/EmployeeViewModel.cs
using DeliverIT.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace DeliverIT.Web.Models.ViewModels
{
    public class EmployeeViewModel : EmployeeWeb
    {
        [Required]
        public string ConfirmPassword { get; set; }
        public SelectList Warehouses { get; set; }
        public SelectList Cities { get; set; }
        public SelectList Countries { get; set; }
    }
}

DeliverIT/Controllers/API/CustomerController.cs
using DeliverIT.Models;
using DeliverIT.Services.DTOs;
using DeliverIT.Services.Exceptions;
using DeliverIT.Services.Services.ServicesInterfaces;
using DeliverIT.Web.Helpers.HelpersContracts;
using Microsoft.AspNetCore.Mvc;

namespace DeliverIT.Web.API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class CustomerController : ControllerBase
    {
        private readonly ICustomerService customerService;
        private readonly IModelMapper modelMapper;
        private readonly IAuthHelper authHelper;

        public CustomerController(ICustomerService customerService, IModelMapper modelMapper, IAuthHelper authHelper)
        {
            this.customerService = customerService;
            this.modelMapper = modelMapper;
            this.authHelper = authHelper;
        }
        [HttpGet("{id}")]
        public IActionResult Get(int id, [FromHeader] string authentication)
        {
            if (!authHelper.MakeCustomerOrEmployeeValidation(id, authentication))
                return this.Unauthorized();
            try
            {
                var customer = customerService.GetById(id);
                var customerDto = new CustomerDto(customer);
                return this.Ok(customerDto);
            }
            catch (EntityNotFoundException)
            {
                return this.NotFound();
            }
        }
        [HttpGet("all")]
        public IActionResult GetAll([FromHeader] string authentication)
        {
            if (!authHelper.MakeEmployeeValidation(authentication))
                return this.Unauthorized();
            var customers = customerService.GetAll();
            return Ok(customers);
        }

        [HttpGet("count")]
        public IActionResult GetCount()
        {
            var count = customerService.GetCount();
            return this.Ok(count);
        }

        //search by email
        [HttpGet("search/email")]
        public IActionResult GetByEmail([FromQuery] string value, [FromHeader] string authentication)
        {
            if (!authHelper.MakeEmployeeValidation(authentication))
                return this.Unauthorized();
            var customer = customerService.GetByEmail(value);
            return this.Ok(customer);
        }

        //customer incoming parcells
        [HttpGet("{id}/parcels/incoming")]
        public IActionResult GetIncomingParcels(int? id, [FromHeader] string authentication)
        {
            if (!authHelper.MakeCustomerOrEmployeeValidation(id, authentication))
                return this.Unauthorized();
            var parcelsForCustomer = customerService.GetIncomingParcels(id);
            return this.Ok(parcelsForCustomer);
        }

        //customer incoming parcells
        [HttpGet("{id}/parcels/past")]
        public IActionResult GetPastParcels(int? id, [FromHeader] string authentication)
        {
            if (!authHelper.MakeCustomerOrEmployeeValidation(id, authentication))
                return this.Unauthorized();
            var parcelsForCustomer = customerService.GetPastParcels(id);
            return this.Ok(parcelsForCustomer);
        }
        [HttpPut("{customerId}/parcels/{parcelId}/delivery/change")]
        public IActionResult ChangeDeliveryStatus(int customerId, int parcelId, [FromHeader] string authentication)
        {
            if (!authHelper.MakeCustomerOrEmployeeValidation(customerId, authentication))
                return this.Unauthorized();
            var message = customerService.ChangeDeliveryStatus(customerId, parcelId);
            if (message == "Error")
                return this.BadRequest();
            return this.Ok(message);
        }

        //filter by multiple
        //first and last name
        [HttpGet("search/name")]
        public IActionResult FilterByFirstAndLastName([FromQuery] string firstname, string lastname, [FromHeader] string authentication)
        {
            if (firstname == null && lastname == null)
            {
                return this.BadRequest();
            }
            if (!authHelper.MakeEmployeeValidation(authentication))
                return this.Unauthorized();
            var filteredCustomers = customerService.FilterByFirstAndLastName(firstname, lastname);
            return this.Ok(filteredCustomers);
        }
        ////search by name
        //[HttpGet("search/name")]
        //public IActionResult GetByName([FromQuery] string value, [FromHeader] string authentication)
        //{
        //    if (!authHelper.MakeEmployeeValidation(authentication))
        //        return this.Unauthorized();
        //    var customer = customerService.GetByName(value);
        //    return this.Ok(customer);
        //}

        //search all fields
        [HttpGet("search/allfields")]
        public IActionResult SearchAllFields([FromQuery] string searchWord, [FromHeader] string authentication)
        {
            if (searchWord == null)
            {
                return this.BadRequest();
            }
            if (!authHelper.MakeEmployeeValidation(authentication))
                return this.Unauthorized();
            var searched = customerService.SearchAllFields(searchWord);
            return this.Ok(searched);
        }

        [HttpPut("{id}")]
        public IActionResult Put(int id, [FromBody] CustomerWeb customerWebModel, [FromHeader] string authentication)
        {
            if (customerWebModel == null)
            {
                return this.BadRequest();
            }
            if (!authHelper.MakeCustomerOrEmployeeValidation(id, authentication))
                return this.Unauthorized();
            try
            {
                var customer = this.modelMapper.ToModel(customerWebModel);
                var result = customerService.Update(id, customer);
                return this.Ok(result);
            }
            catch (EntityNotFoundException)
            {
                return this.NotFound();
            }
        }

        [HttpDelete("{id}")]
        public IActionResult Delete(int id, [FromHeader] string authentication)
        {
            if (!authHelper.MakeCustomerOrEmployeeValidation(id, authentication))
                return this.Unauthorized();
            try
            {
                this.customerService.Delete(id);
                return this.Ok("User deleted");
            }
            catch (EntityNotFoundException)
            {
                return this.NotFound();
            }
        }
    }
}

DeliverIT/Controllers/AdminController.cs
using DeliverIT.Services.Exceptions;
using DeliverIT.Services.Services.ServicesInterfaces;
using DeliverIT.Web.Helpers;
using DeliverIT.Web.Helpers.HelpersContracts;
using DeliverIT.Web.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace DeliverIT.Web.Controllers
{
    public class AdminController : Controller
    {
        private readonly IWarehouseService warehouseService;
        private readonly IEmployeeService employeeService;
        private readonly ICustomerService customerService;
        private readonly IModelMapper modelMapper;
        private readonly IAuthHelper authHelper;
        private readonly ICityService cityService;
        private readonly ICountryService countryService;

        public AdminController(IWarehouseService warehouseService
            , IEmployeeService employeeService
            , ICustomerService customerService
            , IModelMapper modelMapper
            , IAuthHelper authHelper
            , ICityService cityService
            , ICountryService countryService)
        {
            this.warehouseService = warehouseService;
            this.employeeService = employeeService;
            this.customerService = customerService;
            this.modelMapper = modelMapper;
            this.authHelper = authHelper;
            this.cityService = cityService;
            this.countryService = countryService;
        }


        [HttpGet]
        [MyAuthorisation(Role = "Employee")]
        public IActionResult Index()
        {
            ViewData["EmployeeName"] = this.HttpContext.Session.GetString("CurrentUser");
            ViewData["UserId"] = int.Parse(this.HttpContext.Session.GetString("UserId"));
            var employeeId = this.HttpContext.Session.GetString("UserId");
            var allShipments = this.warehouseService.GetIncomingShipments(int.Parse(employeeId));
            return this.View(allShipments);
        }
        [MyAuthorisation(Role = "Employee")]
        public IActionResult Customers()
        {
            var customers = customerService.GetAll();
            return View(customers);
        }
        [MyAuthorisation(Role = "Employee")]
        public IActionResult Employees()
        {
            var employees = employeeService.GetAll();
            return View(employees);

        }
        [HttpPost]
        [MyAuthorisation(Role = "Employee")]
        public IActionResult SearchCustomer(string searchword)
        {
            try
            {
                var customers = this.customerService.SearchAllFields(searchword);
                return this.View("Customers", customers);
            }
            catch (InvalidInputDataException)
            {
                return this.View();
            }

        }


        [HttpPost]
        [MyAuthorisation(Role = "Employee")]
        public IActionResult UpcomingShipment(int warehouseId)
        {
            try
            {
                var upcomingShipment = this.warehouseService.GetNextOrder(warehouseId);
                return this.View("../Shipment/UpcomingShipment", upcomingShipment);
            }
            catch (EntityNotFoundException)
            {
                return this.RedirectToAction(nameof(this.Index));
            }

        }


        [MyAuthorisationAttribute(Role = "Employee")]
        public IActionResult Edit(int id)
        {
            try
            {
                var employee = this.employeeService.GetById(id);
                var customerViewModel = this.modelMapper.ToViewModel(employee);

                return this.EmployeeView(customerViewModel);
            }
            catch (EntityNotFoundException)
            {
                return this.View("Error");
            }
        }
        [MyAuthorisationAttribute(Role = "Employee")]
        [HttpPost]
        public IActionResult Edit(int id, [Bind("FirstName, LastName, Email, Password, Street,CityId,CountryId,ConfirmPassword,WarehouseId")] EmployeeViewModel customerViewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(customerViewModel);
            }

            if (!customerViewModel.Password.Equals(customerViewModel.ConfirmPassword))
            {
                this.ModelState.AddModelError("ConfirmPassword", "Confirm password should match password.");
                return this.View(customerViewModel);
            }
            var user = this.modelMapper.ToModel(customerViewModel);
            this.employeeService.Update(id, user);

            return this.RedirectToAction("Logout", "Account");
        }

        [MyAuthorisation(Role = "Employee")]
        public IActionResult Create()
        {
            var newEmployeeView = new EmployeeViewModel();
            return this.EmployeeView(newEmployeeView);

        }

        [HttpPost]
        [MyAuthorisation(Role = "Employee")]
        public IActionResult Create([Bind("FirstName,LastName,Email,Street,CityId,CountryId,WarehouseId,Password,ConfirmPassword")] EmployeeViewModel employeeView)
        {
            if (!this.ModelState.IsValid)
            {
                return this.EmployeeView(employeeView);
            }

            if (this.authHelper.Exist(employeeView.Email))
            {
                this.ModelState.AddModelError("Email", "User with same email already exists.");
                return this.EmployeeView(employeeView);
            }

            if (!employeeView.Password.Equals(employeeView.ConfirmPassword))
            {
                this.ModelState.AddModelError("ConfirmPassword", "Confirm password should match password.");
                return this.EmployeeView(employeeView);
            }

            try
            {
                var employee = modelMapper.ToModel(employeeView);
                this.employeeService.Create(employee);
                return this.RedirectToAction(nameof(this.Index));
            }
            catch (DuplicateEntityException)
            {
                return View("Error");
            }
        }

        private IActionResult EmployeeView(EmployeeViewModel employeeView)
        {
            employeeView.Warehouses = GetWarehouses();
            employeeView.Cities = GetCities();
            employeeView.Countries = GetCountries();
            return this.View(employeeView);
        }

        private SelectList GetWarehouses()
        {
            var warehouses = this.warehouseService.GetAll();
            return new SelectList(warehouses, "WarehouseId", "Address");
        }
        private SelectList GetCities()
        {
            var cities = this.cityService.GetAll().ToList();
            return new SelectList(cities, "CityId", "City");
        }
        private SelectList GetCountries()
        {
            var countries = this.countryService.GetAll().ToList();
            return new SelectList(countries, "CountryId", "CountryName");
        }


    }
}

DeliverIT/Views/Admin/Create.cshtml
@model DeliverIT.Web.Models.ViewModels.EmployeeViewModel

<div style="margin-top: 20px" class="locationsheader">
    <h2>Create Employee</h2>
    <hr class="solid">
</div>

<form class="accountedit" asp-controller="Admin" asp-action="Create">
    <div class="form-group">
        <label asp-for="FirstName" class="form-label mt-4">First Name</label>
        <span asp-validation-for="FirstName" class="form-error"></span>
        <input asp-for="FirstName" id="pass" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="form-label mt-4">Last Name</label>
        <span asp-validation-for="LastName" class="form-error"></span>
        <input asp-for="LastName" id="pass" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Email" class="form-label mt-4">Email Address</label>
        <span asp-validation-for="Email" class="form-error"></span>
        <input asp-for="Email" id="pass" type="email" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Street" class="form-label mt-4">Street</label>
        <span asp-validation-for="Street" class="form-error"></span>
        <input asp-for="Street" id="pass" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label class="form-label mt-4">City</label>
        <select asp-for="CityId" asp-items="Model.Cities" class="input form-select form-error">
            <option value="0">No Address</option>
        </select>

        <span asp-validation-for="CityId"></span>
    </div>
    <div class="form-group">
        <label class="form-label mt-4">Country</label>
        <select asp-for="CountryId" asp-items="Model.Countries" class="input form-select form-error">
            <option value="0">No Address</option>
        </select>
        <span asp-validation-for="CountryId"></span>
    </div>
    <div class="form-group">
        <label class="form-label mt-4">Workplace: (Warehouse)</label>
        <select asp-for="WarehouseId" asp-items="Model.Warehouses" class="input form-select form-error"></select>
        <span asp-validation-for="WarehouseId"></span>
    </div>
    <div class="form-group">
        <label class="form-label mt-4">Password</label>
        <span asp-validation-for="Password" class="form-error"></span>
        <input asp-for="Password" id="pass" type="password" class="form-control" data-type="password">
    </div>
    <div style="margin-bottom: 2rem;" class="form-group">
        <label asp-for="ConfirmPassword" class="form-label mt-4">Repeat Password</label>
        <span asp-validation-for="ConfirmPassword" class="form-error"></span>
        <input asp-for="ConfirmPassword" id="pass" type="password" class="form-control" data-type="password">
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary rounded submit" value="Create">
    </div>
</form>

DeliverIT/Views/Admin/Customers.cshtml
@model IEnumerable<DeliverIT.Services.DTOs.CustomerDto>

@{ ViewData["Title"] = "Customers"; }
<div class="locationsheader">
    <h2 style="margin-top:20px">Customers</h2>
    <hr class="solid">
</div>

<table class="table table-hover" width="500px">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">FirstName</th>
            <th scope="col">LastName</th>
            <th scope="col">Email</th>
            <th scope="col">Address</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in this.Model)
        {
        <tr>
            <th scope="row">@user.CustomerId</th>
            <td>@user.FirstName</td>
            <td>@user.LastName</td>
            <td>@user.Email</td>
            <td>@user.Address</td>
            <td>
                <button type="button" class="btn btn-secondary rounded">
                    <a asp-controller="Customer" asp-action="Details" asp-route-id="@user.CustomerId" class="button">Details</a>
                </button>
            </td>
        </tr>
        }
    </tbody>
</table>

DeliverIT/Views/Admin/Edit.cshtml
@model DeliverIT.Web.Models.ViewModels.EmployeeViewModel

<div style="margin-top: 20px" class="locationsheader">
    <h2>Edit employee profile</h2>
    <hr class="solid">
</div>

<form class="accountedit" asp-controller="Admin" asp-action="Edit">
    <div class="form-group">
        <label asp-for="FirstName" class="form-label mt-4">First Name</label>
        <span asp-validation-for="FirstName" class="form-error"></span>
        <input asp-for="FirstName" id="pass" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="form-label mt-4">Last Name</label>
        <span asp-validation-for="LastName" class="form-error"></span>
        <input asp-for="LastName" id="pass" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Email" class="form-label mt-4">Email Address</label>
        <span asp-validation-for="Email" class="form-error"></span>
        <input asp-for="Email" id="pass" type="email" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Street" class="form-label mt-4">Street</label>
        <span asp-validation-for="Street" class="form-error"></span>
        <input asp-for="Street" id="pass" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label class="form-label mt-4">City</label>
        <select asp-for="CityId" asp-items="Model.Cities" class="input form-select form-error">
            <option value="0">No Address</option>
        </select>

        <span asp-validation-for="CityId"></span>
    </div>
    <div class="form-group">
        <label class="form-label mt-4">Country</label>
        <select asp-for="CountryId" asp-items="Model.Countries" class="input form-select form-error">
            <option value="0">No Address</option>
        </select>
        <span asp-validation-for="CountryId"></span>
    </div>
    <div class="form-group">
        <label class="form-label mt-4">Workplace: (Warehouse)</label>
        <select asp-for="WarehouseId" asp-items="Model.Warehouses" class="input form-select form-error"></select>
        <span asp-validation-for="WarehouseId"></span>
    </div>
    <div class="form-group">
        <label class="form-label mt-4">Password</label>
        <span asp-validation-for="Password" class="form-error"></span>
        <input asp-for="Password" id="pass" type="password" class="form-control" data-type="password">
    </div>
    <div style="margin-bottom: 2rem;" class="form-group">
        <label asp-for="ConfirmPassword" class="form-label mt-4">Repeat Password</label>
        <span asp-validation-for="ConfirmPassword" class="form-error"></span>
        <input asp-for="ConfirmPassword" id="pass" type="password" class="form-control" data-type="password">
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary rounded submit" value="Create">
    </div>
</form>

DeliverIT/Views/Admin/Employees.cshtml
@model IEnumerable<DeliverIT.Services.DTOs.EmployeeDto>

@{ ViewData["Title"] = "Employees"; }

<div class="locationsheader">
    <h2 style="margin-top:20px">Employees</h2>
    <hr class="solid">
</div>

<table class="table table-hover" width="500px">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">FirstName</th>
            <th scope="col">LastName</th>
            <th scope="col">Email</th>
            <th scope="col">Address</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in this.Model)
        {
            <tr>
                <th scope="row">@user.EmployeeId</th>
                <td>@user.FirstName</td>
                <td>@user.LastName</td>
                <td>@user.Email</td>
                <td>@user.Address</td> 
            </tr>
        }
    </tbody>
</table>

DeliverIT/Views/Admin/Index.cshtml
@model IEnumerable<DeliverIT.Services.DTOs.ShipmentDto>


<div class="admingrid">
    <div id="welcometext" class="locationsheader">
        <span class="personalinfo-text">Welcome admin,  @ViewData["EmployeeName"]</span>
        <hr class="solid">
    </div>
    

    <div class="centered box" style="padding-top: 20px;">
        <span>Create a new employee >>  </span>
        <button type="button" class="btn btn-secondary rounded">
            <a asp-controller="Admin" asp-action="Create" class="button">Create</a>
        </button>
    </div>
    <div class="centered box" style="padding-top: 20px;">
        <span>Edit current profile>>  </span>
        <button type="button" class="btn btn-secondary rounded">
            <a asp-controller="Admin" asp-action="Edit" asp-route-id="@ViewData["UserId"]" class="button">Edit</a>
        </button>
    </div>

    <div id="search1" class="centered">
        <span> Search for customer: </span>
        <form asp-controller="Admin" asp-action="SearchCustomer" class="d-flex">
            <input class="form-control me-sm-2" type="text" name="searchword" placeholder="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>

    <div class="upcoming centered">

        <span> Upcoming shipment </span>
        <form asp-controller="Admin" asp-action="UpcomingShipment" class="d-flex">
            <input class="form-control me-sm-2" type="number" name="warehouseId" placeholder="Warehouse Id">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
    <div class="allshipmentsinwarehouse">
        @if (this.Model.Count() != 0)
        {
            <table class="table table-hover" width="500px">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Origin</th>
                        <th scope="col">Destination</th>
                        <th scope="col">Status</th>
                        <th scope="col">Arrival Date</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (var shipments in this.Model)
                        {
                            <tr>
                                <th scope="row">@shipments.ShipmentId</th>
                                <td>@shipments.Origin</td>
                                <td>@shipments.Destination</td>
                                <td>@shipments.Status</td>
                                <td>@shipments.ArrivalDate</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <span class="smalltext"> *This table represents all the shipments in the warehouse you are working in!</span>
        }
        else
        {
            <span> Currently there are no shipments that need managing in your Warehouse!!!</span>

        }

    </div>

</div>