DeliverIT/Models/ViewModels/WarehouseViewModel.cs
using DeliverIT.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DeliverIT.Web.Models.ViewModels
{
    public class WarehouseViewModel : WarehouseWeb
    {
        public SelectList Cities { get; set; }
        public SelectList Countries { get; set; }
    }
}

DeliverIT/Controllers/API/WarehouseController.cs
using DeliverIT.Models;
using DeliverIT.Services.DTOs;
using DeliverIT.Services.Exceptions;
using DeliverIT.Services.Services.ServicesInterfaces;
using DeliverIT.Web.Helpers.HelpersContracts;
using Microsoft.AspNetCore.Mvc;

namespace DeliverIT.Web.API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class WarehouseController : ControllerBase
    {
        private readonly IWarehouseService warehouseService;
        private readonly IModelMapper modelMapper;
        private readonly IAuthHelper authHelper;

        public WarehouseController(IWarehouseService warehouseService, IModelMapper modelMapper, IAuthHelper authHelper)
        {
            this.warehouseService = warehouseService;
            this.modelMapper = modelMapper;
            this.authHelper = authHelper;
        }

        [HttpGet("{id}")]
        public IActionResult Get(int id)
        {
            try
            {
                var warehouse = warehouseService.Get(id);
                var warehouseDto = new WarehouseDto(warehouse);
                return this.Ok(warehouseDto);
            }
            catch (EntityNotFoundException e)
            {
                return this.NotFound(e.Message);
            }
        }
        [HttpGet("all")]
        public IActionResult GetAll()
        {
            var warehouses = warehouseService.GetAll();
            return this.Ok(warehouses);
        }

        [HttpGet("{id}/nextshipment")]
        public IActionResult GetNextOrder(int id, [FromHeader] string authentication)
        {
            try
            {
                if (!authHelper.MakeEmployeeValidation(authentication))
                    return this.Unauthorized();
                var shipment = warehouseService.GetNextOrder(id);
                return this.Ok(shipment);
            }
            catch (EntityNotFoundException e)
            {
                return this.NotFound(e.Message);
            }
        }
        [HttpPost("")]
        public IActionResult Post([FromBody] WarehouseWeb warehouseWebModel, [FromHeader] string authentication)
        {
            if (!authHelper.MakeEmployeeValidation(authentication))
                return this.Unauthorized();
            try
            {
                var warehouse = this.modelMapper.ToModel(warehouseWebModel);
                var result = this.warehouseService.Create(warehouse);

                return this.Created("post", result);
            }
            catch (DuplicateEntityException e)
            {
                return this.Conflict(e.Message);
            }
        }

        [HttpPut("{id}")]
        public IActionResult Put(int id, [FromBody] WarehouseWeb warehouseWebModel, [FromHeader] string authentication)
        {
            if (warehouseWebModel == null)
            {
                return this.BadRequest();
            }
            if (!authHelper.MakeEmployeeValidation(authentication))
                return this.Unauthorized();
            try
            {
                var warehouse = this.modelMapper.ToModel(warehouseWebModel);
                var result = warehouseService.Update(id, warehouse);
                return this.Ok(result);
            }
            catch (EntityNotFoundException e)
            {
                return this.NotFound(e.Message);
            }
        }

        [HttpDelete("{id}")]
        public IActionResult Delete(int id, [FromHeader] string authentication)
        {
            if (!authHelper.MakeEmployeeValidation(authentication))
                return this.Unauthorized();
            try
            {
                this.warehouseService.Delete(id);
                return this.NoContent();
            }
            catch (EntityNotFoundException e)
            {

                return this.NotFound(e.Message);
            }
        }
    }
}

DeliverIT/Controllers/WarehouseController.cs
using DeliverIT.Services.Exceptions;
using DeliverIT.Services.Services.ServicesInterfaces;
using DeliverIT.Web.Helpers;
using DeliverIT.Web.Helpers.HelpersContracts;
using DeliverIT.Web.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using System.Linq;

namespace DeliverIT.Web.Controllers
{
    public class WarehouseController : Controller
    {
        private readonly IWarehouseService warehouseService;
        private readonly IModelMapper modelMapper;
        private readonly ICityService cityService;
        private readonly ICountryService countryService;

        public WarehouseController(IWarehouseService warehouseService, IModelMapper modelMapper, ICityService cityService, ICountryService countryService)
        {
            this.warehouseService = warehouseService;
            this.modelMapper = modelMapper;
            this.cityService = cityService;
            this.countryService = countryService;
        }
        public IActionResult Index()
        {
            var allWarehouses = warehouseService.GetAll();
            return View(allWarehouses);
        }
        [Route("/warehouse/{id}/nextorder")]
        [MyAuthorisationAttribute(Role = "Employee")]
        public IActionResult Next(int id)
        {
            var nextShipment = warehouseService.GetNextOrder(id);
            return View("../shipment/Details", nextShipment);
        }
        [MyAuthorisationAttribute(Role = "Employee")]
        public IActionResult Create()
        {
            var warehouseViewModel = new WarehouseViewModel();
            return WarehouseView(warehouseViewModel);
        }

        [HttpPost]
        [MyAuthorisationAttribute(Role = "Employee")]
        public IActionResult Create([Bind("Street,CityId,CountryId")] WarehouseViewModel warehouseViewModel)
        {
            if (!ModelState.IsValid)
            {
                return WarehouseView(warehouseViewModel);
            }
            try
            {
                var warehouse = modelMapper.ToModel(warehouseViewModel);
                warehouseService.Create(warehouse);
                return this.RedirectToAction(nameof(this.Index));
            }
            catch (DuplicateEntityException)
            {
                return View("Error");
            }
        }
        [MyAuthorisationAttribute(Role = "Employee")]
        public IActionResult Edit(int id)
        {
            try
            {
                var warehouseToUpdate = warehouseService.Get(id);
                var warehouseViewModel = modelMapper.ToViewModel(warehouseToUpdate);
                return WarehouseView(warehouseViewModel);
            }
            catch (EntityNotFoundException)
            {
                return View("Error");
            }
        }

        [HttpPost]
        [MyAuthorisationAttribute(Role = "Employee")]
        public IActionResult Edit(int id, [Bind("Street,CityId,CountryId")] WarehouseViewModel warehouseViewModel)
        {
            if (!ModelState.IsValid)
            {
                return WarehouseView(warehouseViewModel);
            }
            try
            {
                var warehouse = modelMapper.ToModel(warehouseViewModel);
                warehouseService.Update(id, warehouse);
                return this.RedirectToAction(nameof(this.Index));
            }
            catch (DuplicateEntityException)
            {
                return View("Error");
            }
        }
        [MyAuthorisation(Role = "Employee")]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                this.warehouseService.Delete(id);
            }
            catch (EntityNotFoundException)
            {
                return this.View("Error");
            }

            return this.RedirectToAction(nameof(this.Index));
        }
        private IActionResult WarehouseView(WarehouseViewModel warehouseViewModel)
        {
            warehouseViewModel.Cities = GetCities();
            warehouseViewModel.Countries = GetCountries();
            return View(warehouseViewModel);
        }
        private SelectList GetCities()
        {
            var cities = this.cityService.GetAll().ToList();
            return new SelectList(cities, "CityId", "City");
        }
        private SelectList GetCountries()
        {
            var countries = this.countryService.GetAll().ToList();
            return new SelectList(countries, "CountryId", "CountryName");
        }
    }
}

DeliverIT/Views/Warehouse/Create.cshtml
@{ViewData["Action"] = "Create";}
@model DeliverIT.Web.Models.ViewModels.WarehouseViewModel

    <div style="margin-top: 20px" class="locationsheader">
        <h2>Create</h2>
        <hr class="solid">
    </div>
    <partial name="_WarehouseForm.cshtml" />

DeliverIT/Views/Warehouse/Edit.cshtml
@{ViewData["Action"] = "Edit";}
@model DeliverIT.Web.Models.ViewModels.WarehouseViewModel

    <div style="margin-top: 20px" class="locationsheader">
        <h2>Edit</h2>
        <hr class="solid">
    </div>
    <partial name="_WarehouseForm.cshtml" />

DeliverIT/Views/Warehouse/Index.cshtml
@model IEnumerable<DeliverIT.Services.DTOs.WarehouseDto>
@using Microsoft.AspNetCore.Http;
@{ ViewData["Title"] = "Locations"; }
@{
    this.ViewData["IsAuthenticated"] = this.Context.Session.Keys.Contains("CurrentUser");
    this.ViewData["CurrentUser"] = this.Context.Session.GetString("CurrentUser");
    this.ViewData["UserRole"] = this.Context.Session.GetString("UserRole");
}
<div id="locations" class="container">
    <div class="locationsheader">
        <h2 style="margin-top:20px">Locations</h2>
        @if ((bool)ViewData["IsAuthenticated"])
        {
            @if (ViewData["UserRole"].Equals("Employee"))
            {
                <span>Create a new warehouse >>  </span>
                <button type="button" class="btn btn-secondary rounded">
                    <a asp-controller="Warehouse" asp-action="Create" class="button">Create</a>
                </button>}
        }
        <hr class="solid">
    </div>
    <div class="locationtable">
        <table class="table table-hover" width="500px">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Address</th>
                    @if ((bool)ViewData["IsAuthenticated"])
                    {
                        @if (ViewData["UserRole"].Equals("Employee"))
                        {
                            <th scope="col"></th>
                            <th scope="col"></th>
                        }
                    }
                </tr>
            </thead>
            <tbody>
                @{ int i = 1;
                    foreach (var warehouse in this.Model)
                    {
                        <tr>
                            <th scope="row">@warehouse.WarehouseId</th>
                            <td>@warehouse.Address</td>
                            @if ((bool)ViewData["IsAuthenticated"])
                            {
                                @if (ViewData["UserRole"].Equals("Employee"))
                                {
                                    <td>
                                        <button type="button" class="btn btn-secondary rounded">
                                            <a asp-controller="Warehouse" asp-action="Edit" asp-route-id="@warehouse.WarehouseId" class="button">Edit</a>
                                        </button>
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-primary rounded" data-bs-toggle="modal" data-bs-target="#exampleModal-@warehouse.WarehouseId">
                                            Delete
                                        </button>
                                    </td>
                                }
                            }
                        </tr>
                        <div class="modal" id="exampleModal-@warehouse.WarehouseId">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Delete</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true"></span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Are you sure you want to delete this warehouse?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary rounded" data-bs-dismiss="modal">
                                            <a asp-controller="Warehouse" asp-action="DeleteConfirmed" asp-route-id="@warehouse.WarehouseId" class="button">Yes</a>
                                        </button>
                                        <button type="button" class="btn btn-secondary rounded" data-bs-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
            </tbody>
        </table>
    </div>
    <div class="deliverynote">
        <img src="~/css/Images/Locations.png" height="350px"/>
    </div>
    <div class="deliveryinfo">
        <p>
            These are all the available locations that we ship from and to!
            Contact us if you have a buissnes proposal for opening a new location near you!
            We are looking forward to expanding our company!
        </p>
    </div>
</div>

DeliverIT/Views/Warehouse/_WarehouseForm.cshtml
@model DeliverIT.Web.Models.ViewModels.WarehouseViewModel

    <form asp-action=@ViewData["Action"]>
        <fieldset>
        <div class="form-group">
            <label for="exampleInputEmail1" class="form-label mt-4">Street:</label>
            <span asp-validation-for="Street"></span>
            <input asp-for="Street" required class="form-control" placeholder="Enter street">

        </div>
            <div class="form-group">
                <label for="exampleSelect1" class="form-label mt-4">City:</label>
                <select  required  asp-for="CityId" asp-items="Model.Cities"  class="form-select" id="exampleSelect1">
                  
                </select>
            </div>
            <div class="form-group">
                <label for="exampleSelect1" class="form-label mt-4">Country:</label>
                <select   required  asp-for="CountryId" asp-items="Model.Countries"  class="form-select" id="exampleSelect1">
                </select>
            </div>
          
            <button id="editbutton" type="submit" class="btn btn-primary rounded submit">Submit</button>
        </fieldset>
    </form>